Lab3/Server/Controllers/CountryController.cs
using Data;
using Microsoft.AspNetCore.Mvc;
using Models;

namespace Server.Controllers
{
    public class CountryController : Controller
    {
        private DataService _data;
        public CountryController(DataService data)
        {
            _data = data;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Country country)
        {
            _data.CreateCountry(country);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(string id)
        {
            var country = _data.GetCountry(id);
            return View(country);
        }

        [HttpPost]
        public IActionResult Edit(Country country)
        {
            _data.UpdateCountry(country);
            return RedirectToAction("Index");
        }

        public IActionResult Remove(string id)
        {
            _data.RemoveCountry(id);
            return RedirectToAction("Index");
        }
    }
}

Lab3/Server/Controllers/GameController.cs
using Data;
using Microsoft.AspNetCore.Mvc;
using Models;

namespace Server.Controllers
{
    public class GameController : Controller
    {
        private DataService _data;
        public GameController(DataService data)
        {
            _data = data;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Game game)
        {
            _data.CreateGame(game);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(string id)
        {
            var game = _data.GetGame(id);
            return View(game);
        }

        [HttpPost]
        public IActionResult Edit(Game game)
        {
            _data.UpdateGame(game);
            return RedirectToAction("Index");
        }

        public IActionResult Remove(string id)
        {
            _data.RemoveGame(id);
            return RedirectToAction("Index");
        }
    }
}

Lab3/Server/Controllers/GenreController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Models;

namespace Server.Controllers
{
    public class GenreController : Controller
    {
        private DataService _data;
        public GenreController(DataService data)
        {
            _data = data;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Genre genre)
        {
            _data.CreateGenre(genre);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(string id)
        {
            var genre = _data.GetGenre(id);
            return View(genre);
        }

        [HttpPost]
        public IActionResult Edit(Genre genre)
        {
            _data.UpdateGenre(genre);
            return RedirectToAction("Index");
        }

        public IActionResult Remove(string id)
        {
            _data.RemoveGenre(id);
            return RedirectToAction("Index");
        }
    }
}

Lab3/Server/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Server.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
    }
}

Lab3/Server/Controllers/PublisherController.cs
using Data;
using Microsoft.AspNetCore.Mvc;
using Models;

namespace Server.Controllers
{
    public class PublisherController : Controller
    {
        private DataService _data;
        public PublisherController(DataService data)
        {
            _data = data;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Publisher publisher)
        {
            _data.CreatePublisher(publisher);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(string id)
        {
            var country = _data.GetPublisher(id);
            return View(country);
        }

        [HttpPost]
        public IActionResult Edit(Publisher publisher)
        {
            _data.UpdatePublisher(publisher);
            return RedirectToAction("Index");
        }

        public IActionResult Remove(string id)
        {
            _data.RemovePublisher(id);
            return RedirectToAction("Index");
        }
    }
}

Lab3/Server/Views/Country/Create.cshtml
@model Country

@{
    ViewData["Title"] = "Genres";
}

<div class="text-center">
    <form asp-controller="Country" asp-action="Create" method="POST" enctype="application/x-www-form-urlencoded">
        <input type="hidden" name="Id">
        <input type="text" name="Name">
        <input type="submit" value="Create!">
    </form>
</div>

Lab3/Server/Views/Country/Edit.cshtml
@model Country

@{
    ViewData["Title"] = "Genres";
}

<div class="text-center">
    <form asp-controller="Country" asp-action="Edit" method="POST" enctype="application/x-www-form-urlencoded">
        <input type="hidden" name="Id" value="@Model.Id">
        <input type="text" name="Name" id="@Model.Id" value="@Model.Name">
        <input type="submit" value="Edit!">
    </form>
</div>

Lab3/Server/Views/Country/Index.cshtml
@{
    ViewData["Title"] = "Countries";
}

<div class="text-center">
    <h1 class="display-4">Countries</h1>
    <h2>
        <a asp-controller="Country" asp-action="Create">Create</a>
    </h2>
    
    @foreach (var item in _data.GetCountries())
    {
        <h3>@item.Name</h3>
        <a asp-controller="Country" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
        <a asp-controller="Country" asp-action="Remove" asp-route-id="@item.Id">Remove</a>
    }
</div>

Lab3/Server/Views/Game/Create.cshtml
@model Game

@{
    ViewData["Title"] = "Games";
}

<div class="text-center">
    <form asp-controller="Game" asp-action="Create" method="POST" enctype="application/x-www-form-urlencoded">
        <input type="hidden" name="Id">
        <input type="text" name="Name">
        <select name="Genre">
            @foreach (var item in _data.GetGenres())
            {
                <option value="@item.Id">@item.Name</option>
            }
        </select>
        <select name="Publisher">
            @foreach (var item in _data.GetPublishers())
            {
                <option value="@item.Id">@item.Name</option>
            }
        </select>
        <select name="Country">
            @foreach (var item in _data.GetCountries())
            {
                <option value="@item.Id">@item.Name</option>
            }
        </select>
        <input type="submit" value="Create!">
    </form>
</div>

Lab3/Server/Views/Game/Edit.cshtml
@model Game

@{
    ViewData["Title"] = "Games";
}

<div class="text-center">
    <form asp-controller="Game" asp-action="Edit" method="POST" enctype="application/x-www-form-urlencoded">
        <input type="hidden" name="Id" value="@Model.Id">
        <input type="text" name="Name" value="@Model.Name">
        <select name="Genre">
            @foreach (var item in _data.GetGenres())
            {
                if(item.Id == Model.Genre)
                {
                    <option value="@item.Id" selected>@item.Name</option>
                }
                else { <option value="@item.Id">@item.Name</option> }
            }
        </select>
        <select name="Publisher">
            @foreach (var item in _data.GetPublishers())
            {
                if(item.Id == Model.Publisher)
                {
                    <option value="@item.Id" selected>@item.Name</option>
                }
                else { <option value="@item.Id">@item.Name</option> }
            }
        </select>
        <select name="Country">
            @foreach (var item in _data.GetCountries())
            {
                if(item.Id == Model.Country)
                {
                    <option value="@item.Id" selected>@item.Name</option>
                }
                else { <option value="@item.Id">@item.Name</option> }
            }
        </select>
        <input type="submit" value="Edit!">
    </form>
</div>

Lab3/Server/Views/Game/Index.cshtml
@{
    ViewData["Title"] = "Games";
}

<div class="text-center">
    <h1 class="display-4">Games</h1>
    <h2>
        <a asp-controller="Game" asp-action="Create">Create</a>
    </h2>
    
    @foreach (var item in _data.GetGames())
    {
        <h3>@item.Name</h3>
        <a asp-controller="Game" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
        <a asp-controller="Game" asp-action="Remove" asp-route-id="@item.Id">Remove</a>
    }
</div>

Lab3/Server/Views/Genre/Create.cshtml
@model Genre

@{
    ViewData["Title"] = "Genres";
}

<div class="text-center">
    <form asp-controller="Genre" asp-action="Create" method="POST" enctype="application/x-www-form-urlencoded">
        <input type="hidden" name="Id">
        <input type="text" name="Name">
        <input type="submit" value="Create!">
    </form>
</div>

Lab3/Server/Views/Genre/Edit.cshtml
@model Genre

@{
    ViewData["Title"] = "Genres";
}

<div class="text-center">
    <form asp-controller="Genre" asp-action="Edit" method="POST" enctype="application/x-www-form-urlencoded">
        <input type="hidden" name="Id" value="@Model.Id">
        <input type="text" name="Name" id="@Model.Id" value="@Model.Name">
        <input type="submit" value="Edit!">
    </form>
</div>

Lab3/Server/Views/Genre/Index.cshtml
@{
    ViewData["Title"] = "Genres";
}

<div class="text-center">
    <h1 class="display-4">Genres</h1>
    <h2>
        <a asp-controller="Genre" asp-action="Create">Create</a>
    </h2>
    
    @foreach (var item in _data.GetGenres())
    {
        <h3>@item.Name</h3>
        <a asp-controller="Genre" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
        <a asp-controller="Genre" asp-action="Remove" asp-route-id="@item.Id">Remove</a>
    }
</div>

Lab3/Server/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Hello, kittie gurl</p>
</div>

Lab3/Server/Views/Publisher/Create.cshtml
@model Publisher

@{
    ViewData["Title"] = "Genres";
}

<div class="text-center">
    <form asp-controller="Publisher" asp-action="Create" method="POST" enctype="application/x-www-form-urlencoded">
        <input type="hidden" name="Id">
        <input type="text" name="Name">
        <input type="submit" value="Create!">
    </form>
</div>

Lab3/Server/Views/Publisher/Edit.cshtml
@model Publisher

@{
    ViewData["Title"] = "Genres";
}

<div class="text-center">
    <form asp-controller="Publisher" asp-action="Edit" method="POST" enctype="application/x-www-form-urlencoded">
        <input type="hidden" name="Id" value="@Model.Id">
        <input type="text" name="Name" id="@Model.Id" value="@Model.Name">
        <input type="submit" value="Edit!">
    </form>
</div>

Lab3/Server/Views/Publisher/Index.cshtml
@{
    ViewData["Title"] = "Publishers";
}

<div class="text-center">
    <h1 class="display-4">Publishers</h1>
    <h2>
        <a asp-controller="Publisher" asp-action="Create">Create</a>
    </h2>
    
    @foreach (var item in _data.GetPublishers())
    {
        <h3>@item.Name</h3>
        <a asp-controller="Publisher" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
        <a asp-controller="Publisher" asp-action="Remove" asp-route-id="@item.Id">Remove</a>
    }
</div>

Lab3/Server/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Server</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Server</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Genre" asp-action="Index">Genres</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Country" asp-action="Index">Countries</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Publisher" asp-action="Index">Publishers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Game" asp-action="Index">Games</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Server - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>